parameters:
#    ppe_user.example.class: PPE\UserBundle\Example

services:
#    ppe_user.example:
#        class: %ppe_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
