parameters:
#    pp_ehopital.example.class: PPE\hopitalBundle\Example

services:
#    pp_ehopital.example:
#        class: %pp_ehopital.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
